-- ────────────────────────────────────────────────────────────────────
--  HALO — 非公開メッセージT (2026-06-01)
--
--  純MU哲学(無/引き算/月/ハワイ)の文字だけT。相手ロゴ・実名・歌詞なし。
--  is_active=0 / status='draft' → /shop・新着・sitemap に出ない。
--  /gift/<MU_GIFT_KEY> の非公開ギャラリーからのみ閲覧・購入可能。
--  黒 Bella+Canvas 3001 (product 71), DTG. size→variant: S=4016/M=4017/L=4018
--  価格 ¥4,000 = ONE OK ROCK 公式半袖Tと同額 (store.plusmember.jp 実勢)。
-- ────────────────────────────────────────────────────────────────────

INSERT INTO catalog_brands
  (slug, name, emoji, color_primary, tagline, custom_domain, is_active, revenue_share_pct, config_json)
VALUES
  ('halo', 'HALO', '無', '#0b0b0b',
   '無を、贈る。 · private message tees',
   NULL, 0, 0,
   '{"private":true,"lp_template":null,"design_style":"Sumi-black tee, moon-white Mincho type, text only. Pure MU philosophy (無 / subtraction / moon / island). No partner logo or IP.","ink_default":"white","hero":{"title":"無","subtitle":"private message tees","badge":"2026"}}')
ON CONFLICT(slug) DO UPDATE SET
  name              = excluded.name,
  emoji             = excluded.emoji,
  color_primary     = excluded.color_primary,
  tagline           = excluded.tagline,
  is_active         = excluded.is_active,
  config_json       = excluded.config_json;

INSERT OR IGNORE INTO catalog_products
  (sku, brand, label, description_ja, retail_price_jpy,
   printful_product_id, printful_variant_id, printful_placement,
   printful_print_w, printful_print_h,
   printful_sync_product_id, printful_sync_variant_id,
   stripe_product_id, stripe_price_id,
   design_file, mockup_main_file, mockup_url_external,
   suzuri_url, is_active, sort_order, status, fulfillment_route)
VALUES
  ('HALO-A1MU-S', 'halo', '無 (S)',
   '無 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A1MU.png',
   '/static/halo/preview/preview_HALO-A1MU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A1MU.png',
   NULL, 0, 1, 'draft', 'printful_dtg'),
  ('HALO-A1MU-M', 'halo', '無 (M)',
   '無 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A1MU.png',
   '/static/halo/preview/preview_HALO-A1MU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A1MU.png',
   NULL, 0, 2, 'draft', 'printful_dtg'),
  ('HALO-A1MU-L', 'halo', '無 (L)',
   '無 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A1MU.png',
   '/static/halo/preview/preview_HALO-A1MU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A1MU.png',
   NULL, 0, 3, 'draft', 'printful_dtg'),
  ('HALO-A2TASANAI-S', 'halo', '足さない。 (S)',
   '足さない。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A2TASANAI.png',
   '/static/halo/preview/preview_HALO-A2TASANAI.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A2TASANAI.png',
   NULL, 0, 4, 'draft', 'printful_dtg'),
  ('HALO-A2TASANAI-M', 'halo', '足さない。 (M)',
   '足さない。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A2TASANAI.png',
   '/static/halo/preview/preview_HALO-A2TASANAI.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A2TASANAI.png',
   NULL, 0, 5, 'draft', 'printful_dtg'),
  ('HALO-A2TASANAI-L', 'halo', '足さない。 (L)',
   '足さない。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A2TASANAI.png',
   '/static/halo/preview/preview_HALO-A2TASANAI.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A2TASANAI.png',
   NULL, 0, 6, 'draft', 'printful_dtg'),
  ('HALO-A3NOKORU-S', 'halo', '引いた先に、残るもの。 (S)',
   '引いた先に、残るもの。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A3NOKORU.png',
   '/static/halo/preview/preview_HALO-A3NOKORU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A3NOKORU.png',
   NULL, 0, 7, 'draft', 'printful_dtg'),
  ('HALO-A3NOKORU-M', 'halo', '引いた先に、残るもの。 (M)',
   '引いた先に、残るもの。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A3NOKORU.png',
   '/static/halo/preview/preview_HALO-A3NOKORU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A3NOKORU.png',
   NULL, 0, 8, 'draft', 'printful_dtg'),
  ('HALO-A3NOKORU-L', 'halo', '引いた先に、残るもの。 (L)',
   '引いた先に、残るもの。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A3NOKORU.png',
   '/static/halo/preview/preview_HALO-A3NOKORU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A3NOKORU.png',
   NULL, 0, 9, 'draft', 'printful_dtg'),
  ('HALO-A4NOISE-S', 'halo', 'ノイズを、抜く。 (S)',
   'ノイズを、抜く。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A4NOISE.png',
   '/static/halo/preview/preview_HALO-A4NOISE.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A4NOISE.png',
   NULL, 0, 10, 'draft', 'printful_dtg'),
  ('HALO-A4NOISE-M', 'halo', 'ノイズを、抜く。 (M)',
   'ノイズを、抜く。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A4NOISE.png',
   '/static/halo/preview/preview_HALO-A4NOISE.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A4NOISE.png',
   NULL, 0, 11, 'draft', 'printful_dtg'),
  ('HALO-A4NOISE-L', 'halo', 'ノイズを、抜く。 (L)',
   'ノイズを、抜く。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A4NOISE.png',
   '/static/halo/preview/preview_HALO-A4NOISE.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A4NOISE.png',
   NULL, 0, 12, 'draft', 'printful_dtg'),
  ('HALO-A5KOTOBA-S', 'halo', '言葉が、違うだけ。 (S)',
   '言葉が、違うだけ。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A5KOTOBA.png',
   '/static/halo/preview/preview_HALO-A5KOTOBA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A5KOTOBA.png',
   NULL, 0, 13, 'draft', 'printful_dtg'),
  ('HALO-A5KOTOBA-M', 'halo', '言葉が、違うだけ。 (M)',
   '言葉が、違うだけ。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A5KOTOBA.png',
   '/static/halo/preview/preview_HALO-A5KOTOBA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A5KOTOBA.png',
   NULL, 0, 14, 'draft', 'printful_dtg'),
  ('HALO-A5KOTOBA-L', 'halo', '言葉が、違うだけ。 (L)',
   '言葉が、違うだけ。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-A5KOTOBA.png',
   '/static/halo/preview/preview_HALO-A5KOTOBA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-A5KOTOBA.png',
   NULL, 0, 15, 'draft', 'printful_dtg'),
  ('HALO-B1ISLAND-S', 'halo', '同じ島に、いる。 (S)',
   '同じ島に、いる。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B1ISLAND.png',
   '/static/halo/preview/preview_HALO-B1ISLAND.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B1ISLAND.png',
   NULL, 0, 16, 'draft', 'printful_dtg'),
  ('HALO-B1ISLAND-M', 'halo', '同じ島に、いる。 (M)',
   '同じ島に、いる。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B1ISLAND.png',
   '/static/halo/preview/preview_HALO-B1ISLAND.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B1ISLAND.png',
   NULL, 0, 17, 'draft', 'printful_dtg'),
  ('HALO-B1ISLAND-L', 'halo', '同じ島に、いる。 (L)',
   '同じ島に、いる。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B1ISLAND.png',
   '/static/halo/preview/preview_HALO-B1ISLAND.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B1ISLAND.png',
   NULL, 0, 18, 'draft', 'printful_dtg'),
  ('HALO-B2MOON-S', 'halo', '月は、どこでも同じ。 (S)',
   '月は、どこでも同じ。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B2MOON.png',
   '/static/halo/preview/preview_HALO-B2MOON.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B2MOON.png',
   NULL, 0, 19, 'draft', 'printful_dtg'),
  ('HALO-B2MOON-M', 'halo', '月は、どこでも同じ。 (M)',
   '月は、どこでも同じ。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B2MOON.png',
   '/static/halo/preview/preview_HALO-B2MOON.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B2MOON.png',
   NULL, 0, 20, 'draft', 'printful_dtg'),
  ('HALO-B2MOON-L', 'halo', '月は、どこでも同じ。 (L)',
   '月は、どこでも同じ。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B2MOON.png',
   '/static/halo/preview/preview_HALO-B2MOON.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B2MOON.png',
   NULL, 0, 21, 'draft', 'printful_dtg'),
  ('HALO-B3ALOHA-S', 'halo', '無、と、アロハ。 (S)',
   '無、と、アロハ。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B3ALOHA.png',
   '/static/halo/preview/preview_HALO-B3ALOHA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B3ALOHA.png',
   NULL, 0, 22, 'draft', 'printful_dtg'),
  ('HALO-B3ALOHA-M', 'halo', '無、と、アロハ。 (M)',
   '無、と、アロハ。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B3ALOHA.png',
   '/static/halo/preview/preview_HALO-B3ALOHA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B3ALOHA.png',
   NULL, 0, 23, 'draft', 'printful_dtg'),
  ('HALO-B3ALOHA-L', 'halo', '無、と、アロハ。 (L)',
   '無、と、アロハ。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-B3ALOHA.png',
   '/static/halo/preview/preview_HALO-B3ALOHA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-B3ALOHA.png',
   NULL, 0, 24, 'draft', 'printful_dtg'),
  ('HALO-C1ZAIKO-S', 'halo', 'このTシャツ、在庫ゼロです。 (S)',
   'このTシャツ、在庫ゼロです。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C1ZAIKO.png',
   '/static/halo/preview/preview_HALO-C1ZAIKO.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C1ZAIKO.png',
   NULL, 0, 25, 'draft', 'printful_dtg'),
  ('HALO-C1ZAIKO-M', 'halo', 'このTシャツ、在庫ゼロです。 (M)',
   'このTシャツ、在庫ゼロです。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C1ZAIKO.png',
   '/static/halo/preview/preview_HALO-C1ZAIKO.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C1ZAIKO.png',
   NULL, 0, 26, 'draft', 'printful_dtg'),
  ('HALO-C1ZAIKO-L', 'halo', 'このTシャツ、在庫ゼロです。 (L)',
   'このTシャツ、在庫ゼロです。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C1ZAIKO.png',
   '/static/halo/preview/preview_HALO-C1ZAIKO.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C1ZAIKO.png',
   NULL, 0, 27, 'draft', 'printful_dtg'),
  ('HALO-C2URA-S', 'halo', '用件は、裏に。 (S)',
   '用件は、裏に。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C2URA.png',
   '/static/halo/preview/preview_HALO-C2URA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C2URA.png',
   NULL, 0, 28, 'draft', 'printful_dtg'),
  ('HALO-C2URA-M', 'halo', '用件は、裏に。 (M)',
   '用件は、裏に。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C2URA.png',
   '/static/halo/preview/preview_HALO-C2URA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C2URA.png',
   NULL, 0, 29, 'draft', 'printful_dtg'),
  ('HALO-C2URA-L', 'halo', '用件は、裏に。 (L)',
   '用件は、裏に。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C2URA.png',
   '/static/halo/preview/preview_HALO-C2URA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C2URA.png',
   NULL, 0, 30, 'draft', 'printful_dtg'),
  ('HALO-C3KITEMITA-S', 'halo', '無、着てみた。 (S)',
   '無、着てみた。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C3KITEMITA.png',
   '/static/halo/preview/preview_HALO-C3KITEMITA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C3KITEMITA.png',
   NULL, 0, 31, 'draft', 'printful_dtg'),
  ('HALO-C3KITEMITA-M', 'halo', '無、着てみた。 (M)',
   '無、着てみた。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C3KITEMITA.png',
   '/static/halo/preview/preview_HALO-C3KITEMITA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C3KITEMITA.png',
   NULL, 0, 32, 'draft', 'printful_dtg'),
  ('HALO-C3KITEMITA-L', 'halo', '無、着てみた。 (L)',
   '無、着てみた。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-C3KITEMITA.png',
   '/static/halo/preview/preview_HALO-C3KITEMITA.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-C3KITEMITA.png',
   NULL, 0, 33, 'draft', 'printful_dtg'),
  ('HALO-D1SEIJAKU-S', 'halo', 'いちばん大きな音は、静けさ。 (S)',
   'いちばん大きな音は、静けさ。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-D1SEIJAKU.png',
   '/static/halo/preview/preview_HALO-D1SEIJAKU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-D1SEIJAKU.png',
   NULL, 0, 34, 'draft', 'printful_dtg'),
  ('HALO-D1SEIJAKU-M', 'halo', 'いちばん大きな音は、静けさ。 (M)',
   'いちばん大きな音は、静けさ。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-D1SEIJAKU.png',
   '/static/halo/preview/preview_HALO-D1SEIJAKU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-D1SEIJAKU.png',
   NULL, 0, 35, 'draft', 'printful_dtg'),
  ('HALO-D1SEIJAKU-L', 'halo', 'いちばん大きな音は、静けさ。 (L)',
   'いちばん大きな音は、静けさ。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-D1SEIJAKU.png',
   '/static/halo/preview/preview_HALO-D1SEIJAKU.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-D1SEIJAKU.png',
   NULL, 0, 36, 'draft', 'printful_dtg'),
  ('HALO-D2MANIN-S', 'halo', '満員の、無。 (S)',
   '満員の、無。 · 黒T Bella+Canvas 3001 · DTG · size S',
   4000, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-D2MANIN.png',
   '/static/halo/preview/preview_HALO-D2MANIN.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-D2MANIN.png',
   NULL, 0, 37, 'draft', 'printful_dtg'),
  ('HALO-D2MANIN-M', 'halo', '満員の、無。 (M)',
   '満員の、無。 · 黒T Bella+Canvas 3001 · DTG · size M',
   4000, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-D2MANIN.png',
   '/static/halo/preview/preview_HALO-D2MANIN.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-D2MANIN.png',
   NULL, 0, 38, 'draft', 'printful_dtg'),
  ('HALO-D2MANIN-L', 'halo', '満員の、無。 (L)',
   '満員の、無。 · 黒T Bella+Canvas 3001 · DTG · size L',
   4000, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/halo/d/design_HALO-D2MANIN.png',
   '/static/halo/preview/preview_HALO-D2MANIN.png',
   'https://wearmu.com/static/halo/preview/preview_HALO-D2MANIN.png',
   NULL, 0, 39, 'draft', 'printful_dtg');
