-- ────────────────────────────────────────────────────────────────────
--  MUGON 無言 — MU メッセージT 公開コレクション (2026-06-01)
--
--  墨黒×月白・明朝・文字だけ。普遍的なMUのことば(引き算/静/月/禅)。
--  ⚠ TAKA/家の内輪ネタ(家賃はライブ1本 等)は含めない=非売品。
--  is_active=0/status='draft' → 公開前。確認後 1 に上げて /shop 露出。
--  黒 Bella+Canvas 3001 (product 71) DTG. size→variant: S=4016/M=4017/L=4018
--  価格 ¥4,800。生成りカラー/XLは variant 未検証→別seedで追加。
-- ────────────────────────────────────────────────────────────────────

INSERT INTO catalog_brands
  (slug, name, emoji, color_primary, tagline, custom_domain, is_active, revenue_share_pct, config_json)
VALUES
  ('mugon', 'MUGON 無言', '無', '#0b0b0b',
   '無言。引き算のことば。',
   NULL, 0, 0,
   '{"lp_template":"standard","design_style":"Sumi-black tee, moon-white Mincho W6, text only, deadpan. Pure MU philosophy.","ink_default":"white","hero":{"title":"無言","subtitle":"引き算のことば","badge":"MU"}}')
ON CONFLICT(slug) DO UPDATE SET
  name=excluded.name, emoji=excluded.emoji, color_primary=excluded.color_primary,
  tagline=excluded.tagline, is_active=excluded.is_active, config_json=excluded.config_json;

INSERT OR IGNORE INTO catalog_products
  (sku, brand, label, description_ja, retail_price_jpy,
   printful_product_id, printful_variant_id, printful_placement,
   printful_print_w, printful_print_h,
   printful_sync_product_id, printful_sync_variant_id,
   stripe_product_id, stripe_price_id,
   design_file, mockup_main_file, mockup_url_external,
   suzuri_url, is_active, sort_order, status, fulfillment_route)
VALUES
  ('MUGON-MU-S', 'mugon', '無 (S)',
   '無 · 黒T Bella+Canvas 3001 · DTG ·  · size S',
   4800, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MU.png',
   '/static/mugon/preview/preview_MUGON-MU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MU.png',
   NULL, 0, 1, 'draft', 'printful_dtg'),
  ('MUGON-MU-M', 'mugon', '無 (M)',
   '無 · 黒T Bella+Canvas 3001 · DTG ·  · size M',
   4800, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MU.png',
   '/static/mugon/preview/preview_MUGON-MU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MU.png',
   NULL, 0, 2, 'draft', 'printful_dtg'),
  ('MUGON-MU-L', 'mugon', '無 (L)',
   '無 · 黒T Bella+Canvas 3001 · DTG ·  · size L',
   4800, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MU.png',
   '/static/mugon/preview/preview_MUGON-MU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MU.png',
   NULL, 0, 3, 'draft', 'printful_dtg'),
  ('MUGON-MU-XL', 'mugon', '無 (XL)',
   '無 · 黒T Bella+Canvas 3001 · DTG ·  · size XL',
   4800, 71, 4019, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MU.png',
   '/static/mugon/preview/preview_MUGON-MU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MU.png',
   NULL, 0, 4, 'draft', 'printful_dtg'),
  ('MUGON-TASANAI-S', 'mugon', '足さない。 (S)',
   '足さない。 · 黒T Bella+Canvas 3001 · DTG · Add nothing. · size S',
   4800, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TASANAI.png',
   '/static/mugon/preview/preview_MUGON-TASANAI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TASANAI.png',
   NULL, 0, 5, 'draft', 'printful_dtg'),
  ('MUGON-TASANAI-M', 'mugon', '足さない。 (M)',
   '足さない。 · 黒T Bella+Canvas 3001 · DTG · Add nothing. · size M',
   4800, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TASANAI.png',
   '/static/mugon/preview/preview_MUGON-TASANAI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TASANAI.png',
   NULL, 0, 6, 'draft', 'printful_dtg'),
  ('MUGON-TASANAI-L', 'mugon', '足さない。 (L)',
   '足さない。 · 黒T Bella+Canvas 3001 · DTG · Add nothing. · size L',
   4800, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TASANAI.png',
   '/static/mugon/preview/preview_MUGON-TASANAI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TASANAI.png',
   NULL, 0, 7, 'draft', 'printful_dtg'),
  ('MUGON-TASANAI-XL', 'mugon', '足さない。 (XL)',
   '足さない。 · 黒T Bella+Canvas 3001 · DTG · Add nothing. · size XL',
   4800, 71, 4019, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TASANAI.png',
   '/static/mugon/preview/preview_MUGON-TASANAI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TASANAI.png',
   NULL, 0, 8, 'draft', 'printful_dtg'),
  ('MUGON-NOISE-S', 'mugon', 'ノイズを、抜く。 (S)',
   'ノイズを、抜く。 · 黒T Bella+Canvas 3001 · DTG · Cut the noise. · ♪ mugon.fm/?s=noise · size S',
   4800, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-NOISE.png',
   '/static/mugon/preview/preview_MUGON-NOISE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-NOISE.png',
   NULL, 0, 9, 'draft', 'printful_dtg'),
  ('MUGON-NOISE-M', 'mugon', 'ノイズを、抜く。 (M)',
   'ノイズを、抜く。 · 黒T Bella+Canvas 3001 · DTG · Cut the noise. · ♪ mugon.fm/?s=noise · size M',
   4800, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-NOISE.png',
   '/static/mugon/preview/preview_MUGON-NOISE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-NOISE.png',
   NULL, 0, 10, 'draft', 'printful_dtg'),
  ('MUGON-NOISE-L', 'mugon', 'ノイズを、抜く。 (L)',
   'ノイズを、抜く。 · 黒T Bella+Canvas 3001 · DTG · Cut the noise. · ♪ mugon.fm/?s=noise · size L',
   4800, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-NOISE.png',
   '/static/mugon/preview/preview_MUGON-NOISE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-NOISE.png',
   NULL, 0, 11, 'draft', 'printful_dtg'),
  ('MUGON-NOISE-XL', 'mugon', 'ノイズを、抜く。 (XL)',
   'ノイズを、抜く。 · 黒T Bella+Canvas 3001 · DTG · Cut the noise. · ♪ mugon.fm/?s=noise · size XL',
   4800, 71, 4019, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-NOISE.png',
   '/static/mugon/preview/preview_MUGON-NOISE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-NOISE.png',
   NULL, 0, 12, 'draft', 'printful_dtg'),
  ('MUGON-SEIJAKU-S', 'mugon', '静けさも、強さ。 (S)',
   '静けさも、強さ。 · 黒T Bella+Canvas 3001 · DTG · Stillness is strength. · ♪ mugon.fm/?s=seijaku · size S',
   4800, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-SEIJAKU.png',
   '/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   NULL, 0, 13, 'draft', 'printful_dtg'),
  ('MUGON-SEIJAKU-M', 'mugon', '静けさも、強さ。 (M)',
   '静けさも、強さ。 · 黒T Bella+Canvas 3001 · DTG · Stillness is strength. · ♪ mugon.fm/?s=seijaku · size M',
   4800, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-SEIJAKU.png',
   '/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   NULL, 0, 14, 'draft', 'printful_dtg'),
  ('MUGON-SEIJAKU-L', 'mugon', '静けさも、強さ。 (L)',
   '静けさも、強さ。 · 黒T Bella+Canvas 3001 · DTG · Stillness is strength. · ♪ mugon.fm/?s=seijaku · size L',
   4800, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-SEIJAKU.png',
   '/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   NULL, 0, 15, 'draft', 'printful_dtg'),
  ('MUGON-SEIJAKU-XL', 'mugon', '静けさも、強さ。 (XL)',
   '静けさも、強さ。 · 黒T Bella+Canvas 3001 · DTG · Stillness is strength. · ♪ mugon.fm/?s=seijaku · size XL',
   4800, 71, 4019, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-SEIJAKU.png',
   '/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-SEIJAKU.png',
   NULL, 0, 16, 'draft', 'printful_dtg'),
  ('MUGON-TSUKI-S', 'mugon', '月は、どこでも同じ。 (S)',
   '月は、どこでも同じ。 · 黒T Bella+Canvas 3001 · DTG · Same moon, everywhere. · size S',
   4800, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TSUKI.png',
   '/static/mugon/preview/preview_MUGON-TSUKI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TSUKI.png',
   NULL, 0, 17, 'draft', 'printful_dtg'),
  ('MUGON-TSUKI-M', 'mugon', '月は、どこでも同じ。 (M)',
   '月は、どこでも同じ。 · 黒T Bella+Canvas 3001 · DTG · Same moon, everywhere. · size M',
   4800, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TSUKI.png',
   '/static/mugon/preview/preview_MUGON-TSUKI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TSUKI.png',
   NULL, 0, 18, 'draft', 'printful_dtg'),
  ('MUGON-TSUKI-L', 'mugon', '月は、どこでも同じ。 (L)',
   '月は、どこでも同じ。 · 黒T Bella+Canvas 3001 · DTG · Same moon, everywhere. · size L',
   4800, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TSUKI.png',
   '/static/mugon/preview/preview_MUGON-TSUKI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TSUKI.png',
   NULL, 0, 19, 'draft', 'printful_dtg'),
  ('MUGON-TSUKI-XL', 'mugon', '月は、どこでも同じ。 (XL)',
   '月は、どこでも同じ。 · 黒T Bella+Canvas 3001 · DTG · Same moon, everywhere. · size XL',
   4800, 71, 4019, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-TSUKI.png',
   '/static/mugon/preview/preview_MUGON-TSUKI.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-TSUKI.png',
   NULL, 0, 20, 'draft', 'printful_dtg'),
  ('MUGON-MUSHIN-S', 'mugon', '無心。 (S)',
   '無心。 · 黒T Bella+Canvas 3001 · DTG · No-mind. · size S',
   4800, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MUSHIN.png',
   '/static/mugon/preview/preview_MUGON-MUSHIN.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MUSHIN.png',
   NULL, 0, 21, 'draft', 'printful_dtg'),
  ('MUGON-MUSHIN-M', 'mugon', '無心。 (M)',
   '無心。 · 黒T Bella+Canvas 3001 · DTG · No-mind. · size M',
   4800, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MUSHIN.png',
   '/static/mugon/preview/preview_MUGON-MUSHIN.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MUSHIN.png',
   NULL, 0, 22, 'draft', 'printful_dtg'),
  ('MUGON-MUSHIN-L', 'mugon', '無心。 (L)',
   '無心。 · 黒T Bella+Canvas 3001 · DTG · No-mind. · size L',
   4800, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MUSHIN.png',
   '/static/mugon/preview/preview_MUGON-MUSHIN.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MUSHIN.png',
   NULL, 0, 23, 'draft', 'printful_dtg'),
  ('MUGON-MUSHIN-XL', 'mugon', '無心。 (XL)',
   '無心。 · 黒T Bella+Canvas 3001 · DTG · No-mind. · size XL',
   4800, 71, 4019, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-MUSHIN.png',
   '/static/mugon/preview/preview_MUGON-MUSHIN.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-MUSHIN.png',
   NULL, 0, 24, 'draft', 'printful_dtg'),
  ('MUGON-CAGE-S', 'mugon', '四分三十三秒 (S)',
   '四分三十三秒 · 黒T Bella+Canvas 3001 · DTG · 4''33″ · ♪ mugon.fm/?s=cage · size S',
   4800, 71, 4016, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-CAGE.png',
   '/static/mugon/preview/preview_MUGON-CAGE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-CAGE.png',
   NULL, 0, 25, 'draft', 'printful_dtg'),
  ('MUGON-CAGE-M', 'mugon', '四分三十三秒 (M)',
   '四分三十三秒 · 黒T Bella+Canvas 3001 · DTG · 4''33″ · ♪ mugon.fm/?s=cage · size M',
   4800, 71, 4017, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-CAGE.png',
   '/static/mugon/preview/preview_MUGON-CAGE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-CAGE.png',
   NULL, 0, 26, 'draft', 'printful_dtg'),
  ('MUGON-CAGE-L', 'mugon', '四分三十三秒 (L)',
   '四分三十三秒 · 黒T Bella+Canvas 3001 · DTG · 4''33″ · ♪ mugon.fm/?s=cage · size L',
   4800, 71, 4018, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-CAGE.png',
   '/static/mugon/preview/preview_MUGON-CAGE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-CAGE.png',
   NULL, 0, 27, 'draft', 'printful_dtg'),
  ('MUGON-CAGE-XL', 'mugon', '四分三十三秒 (XL)',
   '四分三十三秒 · 黒T Bella+Canvas 3001 · DTG · 4''33″ · ♪ mugon.fm/?s=cage · size XL',
   4800, 71, 4019, 'front', 2250, 2700, NULL, NULL, NULL, NULL,
   '/static/mugon/d/design_MUGON-CAGE.png',
   '/static/mugon/preview/preview_MUGON-CAGE.png',
   'https://wearmu.com/static/mugon/preview/preview_MUGON-CAGE.png',
   NULL, 0, 28, 'draft', 'printful_dtg');
