#!/usr/bin/env python3
# Dump merch-bridge merch.seed.db → migrations/catalog_seed.sql
# Used once at build time so wearmu Rust ships with the catalog rows baked in
# (idempotent INSERT OR IGNORE on every startup).
#
# After cutover, this script + the merch-bridge repo can be retired.
import sqlite3, json, pathlib, sys

SRC = "/Users/yuki/workspace/merch-bridge/merch.seed.db"
DST = pathlib.Path(__file__).resolve().parent.parent / "migrations" / "catalog_seed.sql"

def q(v):
    if v is None: return "NULL"
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

con = sqlite3.connect(SRC)
con.row_factory = sqlite3.Row

out = []
out.append("-- Generated by scripts/dump_catalog_seed.py — do not edit by hand.")
out.append("-- Source: merch-bridge/merch.seed.db (Python POD catalog being retired).")
out.append("-- Idempotent: every row uses INSERT OR IGNORE; existing rows in wearmu's")
out.append("-- catalog_* tables are preserved as the new source of truth.")
out.append("")

# brands
brands = list(con.execute("SELECT * FROM brands"))
out.append(f"-- {len(brands)} brand rows")
for r in brands:
    out.append(
        "INSERT OR IGNORE INTO catalog_brands "
        "(slug, name, emoji, color_primary, tagline, custom_domain, is_active, revenue_share_pct) "
        f"VALUES ({q(r['slug'])}, {q(r['name'])}, {q(r['emoji'])}, "
        f"{q(r['color_primary'])}, {q(r['tagline'])}, {q(r['custom_domain'])}, "
        f"{r['is_active']}, {r['revenue_share_pct']});"
    )
out.append("")

# products
prods = list(con.execute("SELECT * FROM products WHERE is_active=1"))
out.append(f"-- {len(prods)} active product rows")
for r in prods:
    out.append(
        "INSERT OR IGNORE INTO catalog_products "
        "(sku, brand, label, description_ja, retail_price_jpy, "
        " printful_product_id, printful_variant_id, printful_placement, "
        " printful_print_w, printful_print_h, "
        " printful_sync_product_id, printful_sync_variant_id, "
        " stripe_product_id, stripe_price_id, "
        " design_file, mockup_main_file, mockup_url_external, "
        " suzuri_url, is_active, sort_order) "
        f"VALUES ({q(r['sku'])}, {q(r['brand'])}, {q(r['label'])}, "
        f"{q(r['description_ja'])}, {r['retail_price_jpy']}, "
        f"{r['printful_product_id']}, {r['printful_variant_id']}, "
        f"{q(r['printful_placement'])}, {r['printful_print_w']}, {r['printful_print_h']}, "
        f"{q(r['printful_sync_product_id'])}, {q(r['printful_sync_variant_id'])}, "
        f"{q(r['stripe_product_id'])}, {q(r['stripe_price_id'])}, "
        f"{q(r['design_file'])}, {q(r['mockup_main_file'])}, {q(r['mockup_url_external'])}, "
        f"{q(r['suzuri_url'])}, {r['is_active']}, {r['sort_order']});"
    )
out.append("")

# product_extras
extras = list(con.execute("SELECT * FROM product_extras"))
out.append(f"-- {len(extras)} product_extras rows")
for r in extras:
    out.append(
        "INSERT OR IGNORE INTO catalog_product_extras "
        "(sku, label, image_url, sort_order) "
        f"VALUES ({q(r['sku'])}, {q(r['label'])}, {q(r['image_url'])}, {r['sort_order']});"
    )

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text("\n".join(out) + "\n")
print(f"wrote {DST} ({DST.stat().st_size:,} bytes, {len(brands)} brands, {len(prods)} products, {len(extras)} extras)")
